server:
  port: 8080

spring:
  application:
    name: profiles
  datasource:
    username: 'fatih'
    url: jdbc:postgresql://localhost:5432/profiles
    password: 'admin'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'